<template>
   <div class="flex flex-col lg:flex-row gap-4 mt-4">
        <div class="w-full">
            <!-- Upload Buttons -->
            <div class="flex justify-center gap-2 md:gap-4 mb-4 h-[40px]">
                 <button @click="autoCreateImage"
                    :disabled="showImageGenerate == true"
                    class="w-[35%] sm:w-1/3 bg-orion-button-sec text-white py-2.5 text-xs font-bold lg:text-sm rounded-2xl lg:rounded-2xl text-center hover:bg-cyan-600 flex items-center gap-2 justify-center">
                    Tự động tạo ảnh {{  showImageGenerate == true ? '...' : '' }}
                </button>
                <label id="image_0" class="w-[30%] sm:w-1/3 cursor-pointer bg-orion-button-sec text-white py-2 text-xs font-bold lg:text-sm rounded-2xl lg:rounded-2xl text-center hover:bg-cyan-600 flex items-center gap-2 justify-center">
                    <!-- <div class="rounded-full">
                        <img src="/assets/svgs/upload-icon-w.svg" alt="" class="size-5">
                        </div> -->
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-upload-icon hidden md:show">
                        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                        <polyline points="17 8 12 3 7 8"></polyline>
                        <line x1="12" x2="12" y1="3" y2="15"></line>
                    </svg>
                    <label id="image_upload" class="w-[30%] sm:w-1/3 cursor-pointer bg-orion-button-sec text-white py-2 text-xs font-bold lg:text-sm rounded-2xl lg:rounded-2xl text-center hover:bg-cyan-600 flex items-center gap-2 justify-center">
                        <Upload size="16" color="#ffffff" class="hidden md:show" />
                        <img src="/assets/svgs/aiwow/uploadMedia.svg" alt="" />
                        Tải ảnh
                        <input id="image_upload" type="file" accept="image/*" @change="handleImageUpload($event, 0)" class="hidden" />
                    </label>
                </label>
                <div class="relative w-[30%] sm:w-1/3 text-center">
                    <button class="w-full h-full bg-orion-button-sec text-white font-bold py-2.5 text-xs lg:text-sm rounded-2xl lg:rounded-2xl text-center hover:bg-cyan-600 flex items-center gap-2 justify-center"><img src="/assets/img/my_assistant/generate_image.png" class="hidden md:show size-5" alt=""> Tạo ảnh mới </button>
                </div>
            </div>
            <div class="grid grid-cols-2 items-center justify-center w-full gap-2">
                <div class="flex items-center h-full w-full rounded-xl overflow-hidden min-h-[120px]" v-for="(image, index_image) in images" :key="index_image">
                    <div v-if="image?.imageRef" class="relative m-auto">
                        <input type="checkbox" :checked="checkImage(index_image)" @change="selectImage(index_image)" class="ml-0 top-2 right-2 absolute rounded-full" />
                        <img v-if="image.imageRef" :src="image.imageRef.s3_url" alt="image generated by AI" class="rounded-lg lg:rounded-2xl bg-gray-200 object-contain aspect-[4/3] w-full" />
                        <img v-else :src="image.previewImageUpload" alt="image generated by AI" class="rounded-lg lg:rounded-2xl bg-gray-200 object-contain aspect-[4/3] w-full" />
                        <button type="button" @click="removeImage(index_image)" class="absolute bottom-2 right-2 bg-red-500 text-white w-6 h-6 rounded-full">x</button>
                    </div>
                    <div v-else class="bg-[#E6E6E6] flex h-full items-center justify-center w-full rounded-xl">
                        <div class="flex flex-col items-center" v-if="image.isLoading">
                            <img class="w-24 h-24" src="/assets/img/dashboard/loading.gif" alt="" />
                            <h3 class="text-white text-center">Hệ thống đang xử lý, xin đợi một chút</h3>
                        </div>
                        <img v-else src="/assets/svgs/aiwow/image.svg" alt="loading" class="mx-auto w-16" />
                    </div>
                </div>
            </div>
        </div>
        <!--v-if-->
    </div>
</template>

<script setup>
    import { ref, watch, onMounted, inject, reactive, onUnmounted} from 'vue';
    import { toast } from "vue3-toastify";
    import { eventBus } from "@/lib/eventBus.js";
    const emit = defineEmits(['submit', 'toggle']);
    const props = defineProps({
        results: {
            type: Object,
            default: {
                content:""
            }
        },
        projectId: {
            type: Number,
            default: 0
        },
    });
    const results = ref(props.results)
    function handleUpdateResult(data) {
        results.value.content = data.content;
    }

    onMounted(() => {
        eventBus.on('updateResult', handleUpdateResult);
    });

    const images = ref(props.results.images)

    const selectImage = (index) => {
        images.value[index].is_post = !images.value[index].is_post
        updateData(true)
    }
    
    const checkImage = (index) => {
        return images.value[index].is_post
    };

    const keyword = ref("");
    const searchImages = ref([]);
    const currentPage = ref(1);
    const hasMore = ref(false);
    const colorType = ref("imgColorTypeUndefined");
    const content = ref("Con mèo")

    const canLoadImage = (url) => {
        return new Promise((resolve) => {
            const img = new Image();
            img.onload = () => resolve(true);
            img.onerror = () => resolve(false);
            img.src = url;
        });
    };

    const callSearchImage = async (targetIndex = 0) => {
        try {
            keyword.value = formProject.title || selectedProject?.value?.title

            if (!keyword.value) {
                return;
            }

            isLoading.value = true;

            const response = await axios.get(route("ai-business.search-image"), {
                params: {
                    keyword: keyword.value,
                    color_type: colorType.value,
                    page: currentPage.value,
                    site: selectedProject.value.url || ""
                },
            });
            if (currentPage.value === 1) {
                searchImages.value = response.data.items;
            } else {
                searchImages.value = [...searchImages.value, ...response.data.items];
            }
            let savedCount = 0;
            for (const img of searchImages.value) {
                const imageUrl = img.link;

                const canLoad = await canLoadImage(imageUrl);
                if (canLoad) {
                    await saveGenerationResult(imageUrl);
                    savedCount++;
                }

                if (savedCount >= 4) break;
            }
        } catch (e) {
            console.log(e);
        } finally {
            isLoading.value = false;
        }
    };

    const showImageGenerate = ref(false);
    const autoCreateImage = () => {
        if (showImageGenerate.value) {
            return;
        }
        showImageGenerate.value = !showImageGenerate.value;
        if (showImageGenerate.value) {
            createImage();
        }
    };
    const prompt = ref([
        "Hãy tạo bức ảnh minh họa truyền tải cảm xúc sâu sắc từ bài viết, Ảnh chỉ dùng để hiển thị sản phẩm, không thêm chữ vào ảnh, giúp người xem không chỉ nhìn thấy sản phẩm/dịch vụ mà còn cảm nhận được giá trị tinh thần, lợi ích cảm xúc khi sở hữu nó.  - Chủ đề chính của ảnh: Không tập trung vào sản phẩm, mà khai thác trải nghiệm, cảm giác, giá trị tinh thần mà sản phẩm mang lại.  Hãy đi từ Đối tượng tiềm năng của sản phẩm - sau đó mô tả cảm giác của \"đối tượng\" đó khi sở hữu hoặc sử dụng sản phẩm. Ví dụ:  + Nếu là bất động sản → Cảm giác bình yên, an cư, gắn kết gia đình, sự thành công  + Nếu là sản phẩm công nghệ → Cảm giác hiện đại, tiện lợi, an tâm, kiểm soát tốt hơn cuộc sống + Nếu là sản phẩm sức khỏe → Cảm giác hạnh phúc, tràn đầy năng lượng, an tâm cho gia đình  - Bối cảnh phù hợp với cảm xúc: (VD: ngôi nhà ấm áp với gia đình hạnh phúc, doanh nhân thành đạt tự tin, một người thư giãn tận hưởng thành quả...) - Đảm bảo rằng Không thêm bất kỳ ký tự nào vào ảnh theo bất cứ trường hợp nào 🔥 Hãy đảm bảo hình ảnh không chỉ minh họa sản phẩm/dịch vụ, mà còn đánh trúng vào cảm xúc, giá trị tinh thần mà khách hàng sẽ có được khi sở hữu nó.  Hình ảnh phải trông thực tế nhất có thể",

        "Hãy tạo bức ảnh minh họa trực quan, chủ đề dựa trên Nội dung chính của bài viết, Ảnh chỉ dùng để hiển thị sản phẩm, không thêm chữ vào ảnh. - Đối tượng chính của ảnh: Khai thác từ phần [Nội dung bài viết] - Các yếu tố quan trọng cần minh họa: Hãy tìm kiếm các yếu tố liên quan tới Sản Phẩm / Dịch vụ mà bài viết quảng cáo. Hoặc nếu là bài viết không tập trung vào Sản phẩm/Dịch vụ thì tìm kiếm các yếu tố xung quanh bài viết. - Cảm xúc cần thể hiện: Cần truyền tải được [Cảm xúc mong muốn truyền tải] - Phong cách hình ảnh: Cần truyền tải được [Phong cách viết] - Đảm bảo rằng Không thêm bất kỳ ký tự nào vào ảnh theo bất cứ trường hợp nào - Tông màu và hiệu ứng phù hợp với nội dung: (VD: màu sắc thiên nhiên nếu sản phẩm là hữu cơ, màu sắc công nghệ nếu sản phẩm số...) Hãy đảm bảo mỗi ảnh thể hiện một khía cạnh khác nhau của bài viết, tạo nên sự đồng nhất nhưng không lặp lại. Hình ảnh phải trông thực tế nhất có thể",

        "Hãy tạo bức ảnh minh họa giúp truyền tải mục tiêu chính của bài viết, Ảnh chỉ dùng để hiển thị sản phẩm, không thêm chữ vào ảnh. Sử dụng [Nội dung bài viết] để nắm được đối tượng của bức ảnh. Nhưng Chủ đề Chính sẽ khai thác từ phần [Mục tiêu bài viết] (VD: tăng nhận diện thương hiệu, kích thích mua hàng, xây dựng niềm tin, tạo sự tương tác...) Dựa trên Chủ đề Chính sẽ tạo ra 1 bức ảnh tập trung vào yếu tố mục tiêu bài viết. Và Cảm xúc cần thể hiện: Cần truyền tải được [Cảm xúc mong muốn truyền tải] mà người dùng đã điền. - Đảm bảo rằng Không thêm bất kỳ ký tự nào vào ảnh theo bất cứ trường hợp nào Hãy đảm bảo hình ảnh thể hiện kết quả rõ ràng, giúp người xem dễ dàng cảm nhận được mục tiêu của bài viết. Hình ảnh phải trông thực tế nhất có thể",

        "Hãy tạo bức ảnh với  biểu tượng mạnh mẽ, không minh họa trực tiếp sản phẩm hay nội dung bài viết, Ảnh chỉ dùng để hiển thị sản phẩm, không thêm chữ vào ảnh, mà tập trung vào 1 key cụ thể về giá trị cốt lõi và thông điệp sâu xa của bài viết. - Key chính của bài viết: (Không phải sản phẩm, mà là ý nghĩa sâu xa mà sản phẩm mang lại. VD: \"Thành công\", \"Cân bằng\", \"Hồi sinh\", \"Sự bảo vệ\", \"Phát triển bền vững\"...)  - Hình ảnh biểu tượng để minh họa Key chính: (VD: Kim tự tháp thể hiện sự bền vững, Ngọn lửa tượng trưng cho đam mê, Dòng sông chảy mãi đại diện cho sự phát triển...) - Đảm bảo rằng Không thêm bất kỳ ký tự nào vào ảnh theo bất cứ trường hợp nào Hãy đảm bảo hình ảnh thể hiện kết quả rõ ràng, giúp người xem dễ dàng hiểu được tác động của sản phẩm/dịch vụ. Chú ý hình ảnh thực sự đơn giản, có tính biểu tượng cao, dễ nhớ, gây tò mò và thể hiện rõ thông điệp sâu xa của bài viết. Hình ảnh phải trông thực tế nhất có thể",
    ]);
    const autoCreaeImageLoading = ref(false)
    const createImage = async () => {
        const promises = [];
        //const prompts = getReplacedPrompts();
        const prompt = results.value.content;
        if(!prompt) {
            autoCreaeImageLoading.value = false;
            showImageGenerate.value = false
            toast.error("Nội dung không được để trống");
            return
        }
        for (let index = 0; index < 4; index++) {
            images.value[index].isLoading = true
            let descriptionToSend = prompt
            promises.push(callGenerateImage(descriptionToSend, 0));
        }
        Promise.all(promises)
            .then(() => {
                autoCreaeImageLoading.value = false;
            })
            .finally(() => {
                showImageGenerate.value = false;
            });
    };

    const callGenerateImage = async (finalDescription, index, models) => {
        let attempts = 0;
        const maxRetries = 3;

        while (attempts < maxRetries) {
            try {
                autoCreaeImageLoading.value = true;
                const response = await axios.post(route("ai-image.generate"), {
                    description: finalDescription,
                    style: "Thực tế",
                    artist: "Leonardo da Vinci",
                    height: 1024,
                    width: 1024,
                    model: "Flux Schnell",
                    aspect_ratio: "1:1",
                });
                saveGenerationResult(response?.data, "image", index);
                return;
            } catch (error) {
                attempts++;
                if (error.response && error.response.status === 403) {
                    // showCreditModal();
                    throw error;
                }

                if (attempts >= maxRetries) {
                    console.error(`Gọi API thất bại sau ${attempts} lần thử`, error);
                    throw error;
                }

                console.warn(`Thử lại lần ${attempts}...`);
                await new Promise((resolve) => setTimeout(resolve, 1000));
            }
        }
    };

    const saveGenerationResult = async (dataParam) => {
        const url = dataParam.url || dataParam.generate_file?.s3_url || dataParam;
        try {
            let image = {
                imageRef: {
                    s3_url: url,
                }
            };
            saveImage(image)
        } catch (error) {
            console.error("Lỗi khi lưu kết quả:", error);
            toast.error("Không thể lưu kết quả. Vui lòng thử lại sau.");
            throw error;
        }
    };

    const handleImageUpload = (e, index) => {
        const file = e.target.files[0];
        if (!file) return;
        handleFileChange(e, index);
    };

    const handleFileChange = async (event, index) => {
        if (event.target?.files?.length === 0) {
            return;
        }

        const file = event.target.files[0];

        if (file.type.includes("image")) {
            handleImageStyle(file, index);
            return;
        }

        if (file.type.includes("video")) {
            handleVideoStyle(file, index);
            return;
        }
    };
    let allowedExtension = ["image/jpeg", "image/jpg", "image/png", "video/mp4"];
    const handleImageStyle = async (file, index) => {
        if (allowedExtension.indexOf(file.type) < 0) {
            toast.error("Vui lòng chọn lại ảnh có định dạng .png, .jpg, .jpeg");
            return;
        }

        if (file) {
            let imagePromise = new Promise(function (resolve) {
                const reader = new FileReader();
                reader.onload = () => {
                    let objectURL = URL.createObjectURL(file);
                    resolve(objectURL);
                };
                reader.readAsDataURL(file);
            });
            var s3_url = await getS3URL(file)
            imagePromise.then(function (value) {
                let image = {
                    imageRef: {
                        s3_url: s3_url,
                    }
                };
                saveImage(image)
            });
        }
    };

    const getS3URL = async (file) => {
        const formData = new FormData();
        formData.append("image_file", file);
        try {
            const response = await axios.post(route("short-video.uploadImageToS3"), formData, {
                headers: {
                    "Content-Type": "multipart/form-data",
                },
            });
            if (response.data.success) {
                return response.data.s3_url
            } else {
                return ""
            }
        } catch (err) {
            return ""
        }
    }

    const saveImage = (image) => {
        var isSave = false
        for(var i = 0; i < images.value.length; i++) {
            if(!images.value[i].previewImageUpload && !images.value[i].imageRef && !isSave) {
                isSave = true
                images.value[i] = image;
                images.value[i].isLoading = false
                images.value[i].is_post = false
            }
        }
        updateData()
    }
    const updateData = (isTick = false) => {
        eventBus.emit('updateImages', images);
        const formData = new FormData()
        formData.append("res_images", JSON.stringify(images.value))
        if(isTick) {
            formData.append("is_video", 2)
        }
        emit('updateProject', formData);
    }
    const removeImage = (index) => {
        images.value[index].imageRef = ""
        images.value[index].is_post = false
        updateData()
    }
</script>

