<template>
    <div class="mt-4">
        <!-- Video Section -->
        <div class="flex relative">
            <div class="mb-6 mt-2">
                <p class="text-business-primary font-bold">Video: </p>
            </div>
            <div class="flex absolute w-full justify-center gap-2 md:gap-4 mb-4 h-[40px]">
                <!-- <button @click="autoCreateVideo"
                    :disabled="showVideoGenerate == true"
                    class="w-[35%] sm:w-1/3 bg-aiwow-sec text-white py-2.5 font-bold text-xs lg:text-sm rounded-2xl lg:rounded-2xl text-center hover:bg-cyan-600 flex items-center gap-2 justify-center">
                        Tự động tạo video
                </button>
                <label :id="`video_${index}`" class="w-[35%] sm:w-1/3 bg-aiwow-sec text-white py-2.5 font-bold text-xs lg:text-sm rounded-2xl lg:rounded-2xl text-center hover:bg-cyan-600 flex items-center gap-2 justify-center">
                    <div class="p-1 rounded-full hidden md:show">
                        <Upload size="16" color="#ffffff" />
                    </div>
                    <img src="/assets/svgs/aiwow/uploadMedia.svg" alt="" />
                    Tải video
                    <input type="file" accept="video/mp4,video/x-m4v,video/webm,video/ogg,video/*,.flv,.3gp" class="inputMedia hidden" @change="handleFileChange($event, index)" />
                </label> -->
                <button @click="scrollToCreateFormRef()" class="w-[35%] sm:w-1/3 bg-[#7CCE63] text-white py-2.5 font-bold text-xs lg:text-sm rounded-2xl lg:rounded-2xl text-center hover:bg-cyan-600 flex items-center gap-2 justify-center">
                    <img src="/assets/img/my_assistant/generate_video.png" alt="" class="hidden md:show" />
                    Tạo video mới
                </button>
            </div>
        </div>
       <div class="flex items-center justify-center w-full">
            <label class="text-xs lg:text-sm flex gap-1 items-center mb-1 w-full">
                <div class="flex gap-1 w-full items-center cursor-pointer">
                    <div class="relative w-full">
                        <div v-if="videoRef || previewVideoUpload" class="flex relative items-center justify-center bg-gray-200 rounded-lg lg:rounded-2xl aspect-[4/3] w-full h-full overflow-hidden">
                            <label class="ml-0 top-2 left-2 absolute rounded-full p-2">
                                <input type="checkbox" :checked="checkedVideo" @change="selectVideo()" class="rounded-full checked:bg-[#FFA411] checked:ring-1 checked:ring-[#FFA411] checked:hover:bg-[#FFA411] ring-offset-2 ring-offset-white" />
                            </label>
                            <video controls v-if="videoRef" :src="videoRef" alt="image generated by AI" class="w-auto object-cover max-h-video" />
                            <video controls v-else :src="previewVideoUpload" alt="image generated by AI" class="w-auto object-cover max-h-video" />

                            <button type="button" @click="removeVideo()" class="absolute bottom-2 right-2 bg-red-500 text-white w-6 h-6 rounded-full">x</button>
                        </div>
                        <div v-else class="flex relative items-center justify-center bg-gray-200 rounded-lg lg:rounded-2xl aspect-[4/3] w-full h-full overflow-hidden">
<!--                            <input type="radio" disabled class="bg-gray-200 ml-0 top-2 right-2 absolute rounded-full" />-->
                                <div class="flex flex-col items-center" v-if="isLoadingVideo">
                                <img class="w-24 h-24" src="/assets/img/dashboard/loading.gif" alt="" />
                                <h3 class="text-white text-center">Hệ thống đang xử lý, xin đợi một chút</h3>
                                <span>{{percenLoadingVideo}}%</span>
                            </div>
                            <img v-else src="/assets/img/aiwow/homepage/play_button.png" alt="loading" class="mx-auto w-24" />
                        </div>
                        <div class="absolute top-2 right-2  text-white rounded-full flex justify-center items-center md:gap-2" v-if="!showImageGenerate">
                            <label class="cursor-pointer">
                                <img src="/assets/svgs/upload-icon-v2.svg" />
                                <input type="file" accept="video/mp4,video/x-m4v,video/webm,video/ogg,video/*,.flv,.3gp" class="inputMedia hidden" @change="handleFileChange($event, index)" />
                            </label>
                            <button type="button" @click="autoCreateVideo" class="bg-opacity-30 text-white font-bold bg-black p-[2px] rounded-[4px]">
                                Tự động tạo video
                            </button>
                        </div>
                    </div>
                </div>
            </label>
        </div>
    </div>
</template>

<script setup>
    import { ref, watch, onMounted, inject } from 'vue';
    import { eventBus } from "@/lib/eventBus.js";
    const props = defineProps({
        dataVideo: {
            type: Object,
            default: {
                conent:"",
                images:[]
            }
        },
        results: {
            type: Object,
            default: {
                content:""
            }
        },
        videoRef: {
            type:String
        },
        projectId: {
            type: Number,
            default: 0
        },
    });
    const dataVideo = ref(props.dataVideo)
    const results = ref(props.results)
    function handleUpdateImages(images) {
        dataVideo.value.images = images;
    }

    function handleUpdateResult(data) {
        dataVideo.value.content = data.content;
    }

    const updateDataDetail = (data) => {
        const results =  data.results
        videoRef.value = results.video_url
        dataVideo.value.content = results.content
        checkedVideo.value = results.is_video
        dataVideo.value.images = results.images
    }

    const scrollToCreateFormRef = () => {
        emit("showFormVideo", true)
    }

    const updateContent = (content) => {
        dataVideo.value.content = content
    }

    onMounted(() => {
        eventBus.on('updateImages', handleUpdateImages);
    });

    onMounted(() => {
        eventBus.on('updateResult', handleUpdateResult);
    });
    const emit = defineEmits(['submit', 'toggle']);
    const videoRef = ref(props.videoRef ? props.videoRef :  props.results.video_url)
    const images = ref(props.results.images)
    const previewVideoUpload = ref(null)
    const checkedVideo = ref(false)
    const removeVideo = () => {
        videoRef.value = ""
        previewVideoUpload.value = ""
        const formData = new FormData()
        formData.append("remove_video", true)
        emit('updateProject', formData);
    }
    const selectVideo = () => {
        checkedVideo.value = true
        const formData = new FormData()
        formData.append("is_video", 1)
        emit('updateProject', formData);
    }

    const audioURL = ref(null);
    const taskId = ref(null);
    const videoUrl = ref(null);
    const isCallApi = ref(false);
    const isLoadingVideo = ref(false);
    const showConfirmVideo = ref(false)
    const isConfirm = ref(false)
    const fileVideoUpload = ref(null)

    const createVideoRunway = async (video_des, audioUrl, imageUrl, imageUrl2, is_credit = 0) => {
        const formData = new FormData();
        formData.append("duration", 5);
        formData.append("number_result", 5);
        formData.append("number", 16);
        formData.append("resolution", "9:16");
        formData.append("is_credit", is_credit);
        formData.append("s3_image_url", imageUrl);
        formData.append("audio_url", audioUrl);
        formData.append("s3_image2_url", imageUrl2);
        try {
            const response = await axios.post(route("short-video.create-video-ai"), formData, {
                headers: {
                    "Content-Type": "multipart/form-data",
                },
            });
            if (response.data.success) {
                return response.data.s3_url
            } else {
                return ""
            }
        } catch (err) {
            return ""
        }
    }

    const getS3VideoURL = async (file) => {
        const formData = new FormData();
        formData.append("video_file", file);
        try {
            const response = await axios.post(route("video.uploadVideoToS3"), formData, {
                headers: {
                    "Content-Type": "multipart/form-data",
                },
            });
            if (response.data.success) {
                return response.data.s3_url
            } else {
                return ""
            }
        } catch (err) {
            return ""
        }
    }

    const createVideoPre = async (video_des, audioUrl, imageUrl, imageUrl2, is_credit = false) => {
        const formData = new FormData();
        formData.append("duration", 5);
        formData.append("number_result", 5);
        formData.append("number", 16);
        formData.append("resolution", "9:16");
        formData.append("is_credit", is_credit);
        formData.append("start_image_url", imageUrl);
        formData.append("audio_url", audioUrl);
        formData.append("end_image_url", imageUrl2);
        try {
            const response = await axios.post(route("short-video.create-video-prediction"), formData, {
                headers: {
                    "Content-Type": "multipart/form-data",
                },
            });
            if (response.data.success) {
                return response.data.s3_url
            } else {
                return ""
            }
        } catch (err) {
        return ""
        }
    }

    const textToSpeechGoogle = async (video_des, duration) => {
        try {
            const response = await axios.post(route("short-video.getAudioDes"), {
                video_des: video_des,
                duration:duration
            });
            const result = await axios.post(route("ai-audio.text-to-speech-google"), {
                text: response.data.audio_des,
                duration: duration,
            });
            if (result.data.success) {
                return result.data.data;
            }
        } catch (error) {
            return "";
        }
    };

    const createVideoScene = async (imageUrl, imageUrl2, video_des, is_credit = 0) => {
        var audioUrl = await textToSpeechGoogle(video_des, 5);
        if (!audioUrl) {
            return false;
        }
        var video = await createVideoRunway(video_des, audioUrl, imageUrl, imageUrl2, is_credit)

        if(!video) {
            video = await createVideoPre(video_des, audioUrl, imageUrl, imageUrl2, is_credit)
        }
        return video
    }

    const percenLoadingVideo = ref(0)
    const isMergeVideo = ref(false)
    const isLoadingPercent = ref(false)
    const showVideoGenerate = ref(false)
    let allowedExtension = ["video/mp4", "video/webm", "video/ogg", "video/quicktime"];
    const getImageBlobViaCanvas = (url) => {
        return new Promise((resolve, reject) => {
            const img = new Image();
            img.crossOrigin = 'anonymous';

            img.onload = () => {
                const canvas = document.createElement('canvas');
                canvas.width = img.width;
                canvas.height = img.height;
                const ctx = canvas.getContext('2d');
                ctx.drawImage(img, 0, 0);

                canvas.toBlob((blob) => {
                    if (blob) {
                        resolve(blob);
                    } else {
                        reject(new Error("Không thể chuyển ảnh sang blob"));
                    }
                }, 'image/jpeg');
            };

            img.onerror = () => {
                reject(new Error("Không thể tải ảnh qua canvas"));
            };

            img.src = url;
        });
    };

    const getFileFromImageURL = async (url, index = 0) => {
        const proxyUrl = `/proxy-image?url=${encodeURIComponent(url)}`;

        try {
            const response = await axios.get(proxyUrl, { responseType: 'blob' });
            const blob = response.data;
            const fileName = url.split('/').pop().split('?')[0] || `image-${index}.jpg`;
            return new File([blob], fileName, { type: blob.type });
        } catch (err) {
            console.warn(`Proxy failed for ${url}, try canvas fallback`);
            try {
                const blob = await getImageBlobViaCanvas(url);
                const fileName = `image-${index}.jpg`;
                return new File([blob], fileName, { type: blob.type || 'image/jpeg' });
            } catch (err2) {
                console.error("❌ Không thể xử lý ảnh qua proxy/canvas:", url);
                return null;
            }
        }
    };

    const autoCreateVideo = async () => {
        var video_des = dataVideo.value.content
        if (showVideoGenerate.value || !video_des || dataVideo.value.images.length == 0) {
            return;
        }
        isLoadingVideo.value = true
        showVideoGenerate.value = true;
        percenLoadingVideo.value = 0
        isMergeVideo.value = false
        var images = dataVideo.value.images
        var imageVideos = []
        if(images.length == 0) {
            await createImage()
            return
        } else {
            for (let i = 0; i < images.length; i++) {
                let file = images[i].fileImageUpload;

                if (!file && images[i].imageRef?.s3_url) {
                    file = await getFileFromImageURL(images[i].imageRef.s3_url, i);
                }

                if (file) {
                    const s3_url = await getS3URL(file);
                    if (s3_url) {
                        imageVideos.push(s3_url);
                    } else {
                        console.warn(`❌ Upload S3 thất bại cho ảnh ${i}`);
                    }
                } else {
                    console.warn(`❌ Bỏ qua ảnh ${i} vì không thể xử lý`);
                }
            }
        }

        var duration = 5
        if(imageVideos.length > 2) {
            isMergeVideo.value = true
            duration = 10
        }
        const hasEnoughCredit = await checkCreditVideo(duration);
        if (!hasEnoughCredit) {
            isLoadingVideo.value = false
            showVideoGenerate.value = false;
            return; // Dừng nếu không đủ credit
        }
        isLoadingPercent.value = true
        var image2 = ""
        var video2 = ""
        if(imageVideos.length > 1) {
            image2 = imageVideos[1]
        }
        var is_credit = 0
        if(imageVideos.length <= 2) {
            is_credit = 1
        }
        var video1 = await createVideoScene(imageVideos[0], image2, video_des, is_credit)
        if(!video1) {
            toast.error("Có lỗi xảy ra trong quá trình tạo video");
            isLoadingVideo.value = false
            showVideoGenerate.value = false;
            return
        }
        if(imageVideos.length > 2) {
            image2 = ""
            if(imageVideos.length >= 4) {
                image2 = imageVideos[3]
            }
            video2 = await createVideoScene(imageVideos[2], image2, video_des, is_credit)
            if(!video2) {
                toast.error("Có lỗi xảy ra trong quá trình tạo video");
                isLoadingVideo.value = false
                showVideoGenerate.value = false;
                return
            }
        }

        if(video2) {
            var audioUrl = await textToSpeechGoogle(video_des, 10);
            if (!audioUrl) {
                toast.error("Có lỗi khi tạo âm thanh");
                isLoadingVideo.value = false
                showVideoGenerate.value = false;
                return false;
            }
            var videoMerge = await mergeVideo(video1, video2, audioUrl)
            if(percenLoadingVideo.value < 99) {
                for(var i = percenLoadingVideo.value; i < 100; i++) {
                    if(percenLoadingVideo.value < 99) {
                        await sleep(500)
                        percenLoadingVideo.value = percenLoadingVideo.value + 1
                    }
                }
            }
            handleSaveGenerationResultVideo(videoMerge);
        } else {
            if(percenLoadingVideo.value < 99) {
                for(var i = percenLoadingVideo.value; i < 100; i++) {
                    if(percenLoadingVideo.value < 99) {
                        await sleep(500)
                        percenLoadingVideo.value = percenLoadingVideo.value + 1
                    }
                }
            }
            handleSaveGenerationResultVideo(video1);
        }
        isLoadingVideo.value = false
        showVideoGenerate.value = false;
        isConfirm.value = false
        percenLoadingVideo.value = 0
        isLoadingPercent.value = false
    };
    var count = 0
    setInterval(async () => {
        if(isLoadingPercent.value) {
            count = count + 1
            if(isMergeVideo.value) {
                if(count == 3) {
                    count = 0
                    percenLoadingVideo.value =  percenLoadingVideo.value + 1
                }
            } else {
                percenLoadingVideo.value =  percenLoadingVideo.value + 1
            }

            if(percenLoadingVideo.value > 99) {
                percenLoadingVideo.value = 99
            }
        }
    }, 400)

    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    const handleSaveGenerationResultVideo = (videoUrl) => {
        const formData = new FormData()
        formData.append("res_video_url", videoUrl)
        emit('updateProject', formData);
        videoRef.value = videoUrl
        previewVideoUpload.value = ""
        fileVideoUpload.value = ""
    }
    const getS3URL = async (file) => {
        const formData = new FormData();
        formData.append("image_file", file);
        try {
            const response = await axios.post(route("short-video.uploadImageToS3"), formData, {
                headers: {
                    "Content-Type": "multipart/form-data",
                },
            });
            if (response.data.success) {
                return response.data.s3_url
            } else {
                return ""
            }
        } catch (err) {
            return ""
        }
    }

    const mergeVideo = async(video1, video2, audio_url) => {
        const formData = new FormData();
        formData.append("video1_url", video1);
        formData.append("video2_url", video2);
        formData.append("audio_url", audio_url);
        try {
            const response = await axios.post(route("short-video.merge-video-auto"), formData, {
                headers: {
                    "Content-Type": "multipart/form-data",
                },
            });
            if (response.data.success) {
                return response.data.s3_url
            } else {
                return ""
            }
        } catch (err) {
            return ""
        }
    }

    const checkCreditVideo = async (duration = 5) => {
        try {
            const formData = new FormData();
            formData.append('type', 'gen3-alphaturbo');
            formData.append('number_result', duration);
            // Gọi API để kiểm tra credit của user
            const response = await axios.post(route("credit.check_credit"), formData);
            if (response.data.success) {
                // Đủ credit để tiếp tục
                return true;
            } else if (response.data.is_vip_expired) {
                showAffKeyPopup.value = true;
                if (response.data.affCode == "aff_trial") {
                    popupMessage.value = " Gói của bạn đã hết hạn. Xin vui lòng gia hạn tài khoản để tiếp tục sử dụng tính năng này.";
                    acceptUpgrade.value = false;
                }
                return false;
            } else {
                const currentCredit = pageProps.auth.user.credit || 0;
                const additionalCredit = response?.data?.data?.total_price - currentCredit;
                eventBus.emit("popup-buy-credit", { currentCredit, additionalCredit, showBuyCreditPopup: true });
                return false;
            }
        } catch (error) {
            console.error("Đã xảy ra lỗi khi kiểm tra credit:", error);
            toast.error("Không thể kiểm tra credit. Vui lòng thử lại.");
            if (error.response && error.response.status === 422) {
                const errors = error.response.data.errors;
                Object.values(errors).forEach((errorMessages) => {
                    if (Array.isArray(errorMessages)) {
                        errorMessages.forEach((error) => {
                            toast.error(error);
                        });
                    } else {
                        toast.error(errorMessages);
                    }
                });
            } else {
                if (error.response) {
                    toast.error(error.response.data.message || "Đã xảy ra lỗi.");
                } else if (error.request) {
                    toast.error("Không thể kết nối đến server.");
                } else {
                    toast.error("Lỗi: " + error.message);
                }
            }
            return false;
        }
    };

    const handleFileChange = async (event, index) => {
        if (event.target?.files?.length === 0) {
            return;
        }

        const file = event.target.files[0];
        if (file.type.includes("video")) {
            handleVideoStyle(file, index);
            return;
        }
    };

    const handleVideoStyle = async(file, index) => {
        showVideoGenerate.value = true;
        if (allowedExtension.indexOf(file.type) < 0) {
            toast.error("Vui lòng chọn lại video có định dạng .mp4");
            showVideoGenerate.value = false;
            return;
        }

        if (file) {
            var videoUrl = await getS3VideoURL(file)
            videoRef.value = videoUrl
            handleSaveGenerationResultVideo(videoRef.value)
        }
    };
    defineExpose({ handleSaveGenerationResultVideo, updateContent, updateDataDetail });
</script>
