<template>
  <div class="flex flex-col lg:flex-row gap-4 mt-4">
    <div class="w-full">
            <!-- Upload Buttons -->
             <!-- <div class="flex justify-center gap-2 md:gap-4 mb-4 h-[40px]">
                 <button @click="autoCreateImage"
                    :disabled="showImageGenerate == true"
                    class="w-[35%] sm:w-1/3 bg-ai3goc-sec text-white py-2.5 text-xs font-bold lg:text-sm rounded-2xl lg:rounded-2xl text-center hover:bg-cyan-600 flex items-center gap-2 justify-center">
                    Tự động tạo ảnh {{  showImageGenerate == true ? '...' : '' }}
                </button>
                <label id="image_0" class="w-[30%] sm:w-1/3 cursor-pointer bg-ai3goc-sec text-white py-2 text-xs font-bold lg:text-sm rounded-2xl lg:rounded-2xl text-center hover:bg-cyan-600 flex items-center gap-2 justify-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-upload-icon hidden md:show">
                        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                        <polyline points="17 8 12 3 7 8"></polyline>
                        <line x1="12" x2="12" y1="3" y2="15"></line>
                    </svg>
                    <label id="image_upload" class="cursor-pointer bg-ai3goc-sec text-white py-2 text-xs font-bold lg:text-sm rounded-2xl lg:rounded-2xl text-center hover:bg-cyan-600 flex items-center gap-2 justify-center">
                        <Upload size="16" color="#ffffff" class="hidden md:show" />
                        <img src="/assets/svgs/aiwow/uploadMedia.svg" alt="" />
                        Tải ảnh
                        <input id="image_upload" type="file" accept="image/*" @change="handleImageUpload($event, 0)" class="hidden" />
                    </label>
                </label>
                <div class="relative w-[30%] sm:w-1/3 text-center">
                    <button @click="isGenerateImage = !isGenerateImage"  class="w-full h-full bg-ai3goc-sec text-white font-bold py-2.5 text-xs lg:text-sm rounded-2xl lg:rounded-2xl text-center hover:bg-cyan-600 flex items-center gap-2 justify-center">
                        <img src="/assets/img/my_assistant/generate_image.png" class="hidden md:show size-5" alt=""> Tạo ảnh mới
                    </button>
                    <div v-if="isGenerateImage" class="absolute z-10 right-0 w-52 bg-white shadow-xl rounded-2xl p-2 py-4 space-y-2">
                        <div @click="toggleGenerateImage('textToImage', index)" class="flex items-center cursor-pointer text-xs md:text-sm px-4 py-2 hover:bg-[#DEECFF] rounded-md">
                            <p>Tạo ảnh từ văn bản</p>
                        </div>
                        <div @click="toggleGenerateImage('background', index)" class="flex items-center cursor-pointer text-xs md:text-sm px-4 py-2 hover:bg-[#DEECFF] rounded-md">
                            <p>Hình phối cảnh</p>
                        </div>
                    </div>
                </div>
            </div> -->
            <div class="mb-6 mt-2">
                <p class="text-business-primary font-bold">Hình ảnh: </p>
            </div>
            <div class="grid grid-cols-2 items-center justify-center w-full gap-2">
                <div class="bg-[#E6E6E6] flex flex-col justify-center items-center h-full items-center justify-center w-full rounded-xl min-h-[400px]" v-for="(image, index_image) in images" :key="index_image">
                    <div class="relative m-auto" v-if="image.imageRef.s3_url && !image.isLoading">
                        <input v-if="image.imageRef.s3_url" type="checkbox" :checked="checkImage(index_image)" @click="selectImage(index_image)" class="ml-0 top-2 left-2 absolute rounded-full" />
                        <div class="bg-[#E6E6E6] flex h-full items-center justify-center w-full rounded-xl min-h-[400px]">
                              <img v-if="image.imageRef.s3_url" :src="image.imageRef.s3_url" alt="image generated by AI" class="rounded-lg lg:rounded-2xl bg-gray-200 object-contain aspect-[4/3] w-full" />
                            <img v-else src="/assets/svgs/aiwow/image.svg" alt="loading" class="mx-auto w-16" />
                        </div>
                        <div class="absolute top-2 right-2  text-white rounded-full flex justify-center items-center md:gap-2" v-if="!showImageGenerate">
                            <label class="cursor-pointer">
                                <input
                                    type="file"
                                    accept="image/*"
                                    @change="handleImageUpload($event, index_image)"
                                    class="hidden"
                                />
                                <img src="/assets/svgs/upload-icon-v2.svg" />
                            </label>
                            <button type="button" @click="openSearchModal(index, index_image)" >
                                <img src="/assets/svgs/find-icon.svg"/>
                            </button>
                            <button type="button" @click="generateCustomeImage(index_image)" class="bg-opacity-30 text-white font-bold bg-black p-[2px] rounded-[4px]">
                                Tạo lại ảnh
                            </button>
                        </div>
                        <button v-if="image.imageRef.s3_url" type="button" @click="removeImage(index_image)" class="absolute bottom-2 left-2 bg-red-500 text-white w-4 h-4 rounded-full flex justify-center items-center">
                            <img src="/assets/svgs/remove-icon.svg"/>
                        </button>
                        <button v-if="image.imageRef.s3_url" @click="upscaleImage(index_image, image.imageRef.s3_url)" class="absolute bottom-2 right-2 rounded-[7.4px] text-white bg-black bg-opacity-30 flex justify-center items-center px-1 py-[2px] font-bold" type="button">
                            <img class="w-4 h-4" src="/assets/svgs/star-icon.svg"/>
                            Làm nét</button>
                    </div>
                    <div v-else class="bg-[#E6E6E6] flex h-full items-center justify-center w-full rounded-xl relative">
                        <div class="flex flex-col items-center" v-if="image.isLoading || showImageGenerate">
                            <img class="w-24 h-24" src="/assets/img/dashboard/loading.gif" alt="" />
                            <h3 class="text-white text-center">Hệ thống đang xử lý, xin đợi một chút</h3>
                        </div>
                        <img v-else src="/assets/svgs/aiwow/image.svg" alt="loading" class="mx-auto w-16" />
                        <div v-if="!image.isLoading && !showImageGenerate" class="absolute top-2 right-2  text-white rounded-full flex justify-center items-center md:gap-2">
                            <label class="cursor-pointer">
                                <input
                                    type="file"
                                    accept="image/*"
                                    @change="handleImageUpload($event, index_image)"
                                    class="hidden"
                                />
                                <img src="/assets/svgs/upload-icon-v2.svg" />
                            </label>
                            <button type="button" @click="openSearchModal(index, index_image)" >
                                <img src="/assets/svgs/find-icon.svg"/>
                            </button>
                            <button type="button" @click="generateCustomeImage(index_image)" class="bg-opacity-30 text-white font-bold bg-black p-[2px] rounded-[4px]">
                                Tạo lại ảnh
                            </button>
                        </div>
                    </div>
                    <h2 class="italic mt-1">{{ label_images[image.type_image ? image.type_image : 4] }}</h2>
                </div>
            </div>
        </div>
        <!--v-if-->
    </div>
        <div v-if="showSearchModal" class="fixed inset-0 z-50 bg-black bg-opacity-50 flex justify-center items-center">
        <div class="bg-white w-[80vw] md:w-[50vw] p-4 rounded-xl">
            <div class="flex items-center justify-between">
                <div class="flex justify-start items-center gap-4">
                    <img src="/assets/img/ai3goc/logo/logo_img.svg" alt="step" class="w-[24px] h-auto" />
                    <span class="text-[15px] lg:text-[18px] leading-none font-bold text-black">Tìm kiếm hình ảnh</span>
                </div>
                <button type="button" @click="showSearchModal = false" class="p-2 rounded-full bg-gray-300">
                    <img src="/assets/svgs/remove-icon.svg"/>
                </button>
            </div>
            <div class="border-t border-gray-300 my-2"></div>
            <div class="grid grid-cols-2 md:grid-cols-3 gap-4 max-h-[60vh] overflow-y-auto">
                <div
                    v-for="(img, i) in searchImages"
                    :key="i"
                    @click="selectedSearchImage = img.link"
                    :class="[
                        'cursor-pointer border-2 rounded-lg overflow-hidden',
                        selectedSearchImage === img.link ? 'border-blue-500' : 'border-transparent'
                    ]"
                >
                    <img :src="img.link" class="w-full aspect-[4/3] object-cover" />
                </div>
                <div class="flex justify-center items-center">
                    <button type="button" @click="loadMoreImages" :disabled="isLoadingMore" :class="isLoadingMore ? 'bg-opacity-60' : 'bg-opacity-100'" class="min-w-[100px] md:min-w-[150px] h-fit px-2 py-2 lg rounded-lg lg:rounded-2xl border border-[#C5C5C5] text-white font-bold place-items-center gap-2 text-sm bg-[#37009A]">{{ isLoadingMore ? 'Đang tải thêm ảnh...' : 'Xem thêm...' }} </button>
                </div>
            </div>
            <div class="flex justify-center items-center my-4">
                <button @click="confirmSelectedImage" class="min-w-[100px] md:min-w-[150px] px-2 py-2 lg bg-ai3goc-primary rounded-lg lg:rounded-2xl border border-[#C5C5C5] text-white font-bold place-items-center gap-2 text-sm">Xác nhận</button>
            </div>
        </div>
    </div>
</template>

<script setup>
    import { ref, watch, onMounted, inject, reactive, onUnmounted} from 'vue';
    import { toast } from "vue3-toastify";
    import { eventBus } from "@/lib/eventBus.js";
    const emit = defineEmits(['submit', 'toggle']);
    const props = defineProps({
        facebookContentDetail: {
            type: Object,
            default: {
                content:""
            }
        },
        selectedProject: {
            type: Object,
            default: {
                content:""
            }
        },
        projectId: {
            type: Number,
            default: 0
        },
    });

    const facebookContentDetail = ref(props.facebookContentDetail)
    const selectedProject = ref(props.selectedProject)
    console.log(selectedProject, 'selectedProject');
    function handleUpdateResult(data) {
        facebookContentDetail.value = data;
    }

    onMounted(() => {
        eventBus.on('updateFaceBookContent', handleUpdateResult);
    });
    const images = ref(props.facebookContentDetail.images)

    const toggleGenerateImage = (type) => {
        isGenerateImage.value = false
        emit("toggleGenerateImage", type)
    }

    const selectImage = (index) => {
        images.value[index].is_post = !images.value[index].is_post
        updateData(true)
    }
    const isGenerateImage = ref(false)
    const checkImage = (index) => {
        return images.value[index].is_post
    };
    const keyword = ref("");
    const searchImages = ref([]);
    const currentPage = ref(1);
    const hasMore = ref(false);
    const colorType = ref("imgColorTypeUndefined");
    const content = ref("Con mèo")
    const canLoadImage = (url) => {
        return new Promise((resolve) => {
            const img = new Image();
            img.onload = () => resolve(true);
            img.onerror = () => resolve(false);
            img.src = url;
        });
    };

    const showImageGenerate = ref(false);
    const autoCreateImage = async(isAuto = false) => {
        var modelProject = selectedProject.value?.model_product
        var imageProject = selectedProject.value?.image_product
        if(!modelProject && !imageProject) {
            for(var idx = 0; idx < 4; idx ++) {
                images.value[idx].isLoading = true
                images.value[idx].imageRef = {};
            }
            await searchImageByKeyword(true);
            return
        }
        if (showImageGenerate.value) {
            return;
        }
        const promises = [];
        showImageGenerate.value = !showImageGenerate.value;
        if (showImageGenerate.value) {
            await updateImageType()
            for(var idx = 0; idx < 4; idx ++) {
                images.value[idx].isLoading = true
                images.value[idx].imageRef = {};
            }
            for (let index = 0; index < 4; index++) {
                promises.push(createImageBy(index, isAuto));
            }
            Promise.all(promises).then(() => {
                showImageGenerate.value = false;
            });
        }
    };
    const prompts = ref([
        "Hãy tạo bức ảnh minh họa truyền tải cảm xúc sâu sắc từ bài viết, Ảnh chỉ dùng để hiển thị sản phẩm, không thêm chữ vào ảnh, giúp người xem không chỉ nhìn thấy sản phẩm/dịch vụ mà còn cảm nhận được giá trị tinh thần, lợi ích cảm xúc khi sở hữu nó.  - Chủ đề chính của ảnh: Không tập trung vào sản phẩm, mà khai thác trải nghiệm, cảm giác, giá trị tinh thần mà sản phẩm mang lại.  Hãy đi từ Đối tượng tiềm năng của sản phẩm - sau đó mô tả cảm giác của \"đối tượng\" đó khi sở hữu hoặc sử dụng sản phẩm. Ví dụ:  + Nếu là bất động sản → Cảm giác bình yên, an cư, gắn kết gia đình, sự thành công  + Nếu là sản phẩm công nghệ → Cảm giác hiện đại, tiện lợi, an tâm, kiểm soát tốt hơn cuộc sống + Nếu là sản phẩm sức khỏe → Cảm giác hạnh phúc, tràn đầy năng lượng, an tâm cho gia đình  - Bối cảnh phù hợp với cảm xúc: (VD: ngôi nhà ấm áp với gia đình hạnh phúc, doanh nhân thành đạt tự tin, một người thư giãn tận hưởng thành quả...) - Đảm bảo rằng Không thêm bất kỳ ký tự nào vào ảnh theo bất cứ trường hợp nào 🔥 Hãy đảm bảo hình ảnh không chỉ minh họa sản phẩm/dịch vụ, mà còn đánh trúng vào cảm xúc, giá trị tinh thần mà khách hàng sẽ có được khi sở hữu nó.  Hình ảnh phải trông thực tế nhất có thể",
        "Hãy tạo bức ảnh minh họa trực quan, chủ đề dựa trên Nội dung chính của bài viết, Ảnh chỉ dùng để hiển thị sản phẩm, không thêm chữ vào ảnh. - Đối tượng chính của ảnh: Khai thác từ phần [Nội dung bài viết] - Các yếu tố quan trọng cần minh họa: Hãy tìm kiếm các yếu tố liên quan tới Sản Phẩm / Dịch vụ mà bài viết quảng cáo. Hoặc nếu là bài viết không tập trung vào Sản phẩm/Dịch vụ thì tìm kiếm các yếu tố xung quanh bài viết. - Cảm xúc cần thể hiện: Cần truyền tải được [Cảm xúc mong muốn truyền tải] - Phong cách hình ảnh: Cần truyền tải được [Phong cách viết] - Đảm bảo rằng Không thêm bất kỳ ký tự nào vào ảnh theo bất cứ trường hợp nào - Tông màu và hiệu ứng phù hợp với nội dung: (VD: màu sắc thiên nhiên nếu sản phẩm là hữu cơ, màu sắc công nghệ nếu sản phẩm số...) Hãy đảm bảo mỗi ảnh thể hiện một khía cạnh khác nhau của bài viết, tạo nên sự đồng nhất nhưng không lặp lại. Hình ảnh phải trông thực tế nhất có thể",
        "Hãy tạo bức ảnh minh họa giúp truyền tải mục tiêu chính của bài viết, Ảnh chỉ dùng để hiển thị sản phẩm, không thêm chữ vào ảnh. Sử dụng [Nội dung bài viết] để nắm được đối tượng của bức ảnh. Nhưng Chủ đề Chính sẽ khai thác từ phần [Mục tiêu bài viết] (VD: tăng nhận diện thương hiệu, kích thích mua hàng, xây dựng niềm tin, tạo sự tương tác...) Dựa trên Chủ đề Chính sẽ tạo ra 1 bức ảnh tập trung vào yếu tố mục tiêu bài viết. Và Cảm xúc cần thể hiện: Cần truyền tải được [Cảm xúc mong muốn truyền tải] mà người dùng đã điền. - Đảm bảo rằng Không thêm bất kỳ ký tự nào vào ảnh theo bất cứ trường hợp nào Hãy đảm bảo hình ảnh thể hiện kết quả rõ ràng, giúp người xem dễ dàng cảm nhận được mục tiêu của bài viết. Hình ảnh phải trông thực tế nhất có thể",
        "Hãy tạo bức ảnh với  biểu tượng mạnh mẽ, không minh họa trực tiếp sản phẩm hay nội dung bài viết, Ảnh chỉ dùng để hiển thị sản phẩm, không thêm chữ vào ảnh, mà tập trung vào 1 key cụ thể về giá trị cốt lõi và thông điệp sâu xa của bài viết. - Key chính của bài viết: (Không phải sản phẩm, mà là ý nghĩa sâu xa mà sản phẩm mang lại. VD: \"Thành công\", \"Cân bằng\", \"Hồi sinh\", \"Sự bảo vệ\", \"Phát triển bền vững\"...)  - Hình ảnh biểu tượng để minh họa Key chính: (VD: Kim tự tháp thể hiện sự bền vững, Ngọn lửa tượng trưng cho đam mê, Dòng sông chảy mãi đại diện cho sự phát triển...) - Đảm bảo rằng Không thêm bất kỳ ký tự nào vào ảnh theo bất cứ trường hợp nào Hãy đảm bảo hình ảnh thể hiện kết quả rõ ràng, giúp người xem dễ dàng hiểu được tác động của sản phẩm/dịch vụ. Chú ý hình ảnh thực sự đơn giản, có tính biểu tượng cao, dễ nhớ, gây tò mò và thể hiện rõ thông điệp sâu xa của bài viết. Hình ảnh phải trông thực tế nhất có thể",
    ]);
    const autoCreaeImageLoading = ref(false)
    const createImage = async () => {
        const promises = [];
        const prompt = facebookContentDetail.value.content;
        if(!prompt) {
            autoCreaeImageLoading.value = false;
            showImageGenerate.value = false
            toast.error("Nội dung không được để trống");
            return
        }
        const response = await axios.post(route("ai-business.summarize-content"), {
            content: prompt,
            project_name: "tÔI LÀ AI",
        });
        for (let index = 0; index < 4; index++) {
            images.value[index].isLoading = true
            let descriptionToSend = prompt
            promises.push(callGenerateImage(descriptionToSend, 0));
        }
        Promise.all(promises).then(() => {
            autoCreaeImageLoading.value = false;
        });
    };
    const callGenerateImage = async (finalDescription, index, models) => {
        let attempts = 0;
        const maxRetries = 3;
        while (attempts < maxRetries) {
            try {
                autoCreaeImageLoading.value = true;
                const response = await axios.post(route("ai-image.generate"), {
                    description: finalDescription,
                    style: "Thực tế",
                    artist: "Leonardo da Vinci",
                    height: 1024,
                    width: 1024,
                    model: "Flux Schnell",
                    aspect_ratio: "1:1",
                });
                saveGenerationResult(response?.data, "image", index);
                return;
            } catch (error) {
                attempts++;
                if (error.response && error.response.status === 403) {
                    // showCreditModal();
                    throw error;
                }
                if (attempts >= maxRetries) {
                    console.error(`Gọi API thất bại sau ${attempts} lần thử`, error);
                    throw error;
                }
                console.warn(`Thử lại lần ${attempts}...`);
                await new Promise((resolve) => setTimeout(resolve, 1000));
            }
        }
    };
    const saveGenerationResult = async (dataParam) => {
        const url = dataParam.url || dataParam.generate_file?.s3_url || dataParam;
        try {
            let image = {
                imageRef: {
                    s3_url: url,
                }
            };
            saveImage(image)
        } catch (error) {
            console.error("Lỗi khi lưu kết quả:", error);
            toast.error("Không thể lưu kết quả. Vui lòng thử lại sau.");
            throw error;
        }
    };
    const handleImageUpload = (e, index) => {
        const file = e.target.files[0];
        if (!file) return;
        handleFileChange(e, index);
    };
    const handleFileChange = async (event, index) => {
        if (event.target?.files?.length === 0) {
            return;
        }
        const file = event.target.files[0];
        if (file.type.includes("image")) {
            handleImageStyle(file, index);
            return;
        }
        if (file.type.includes("video")) {
            handleVideoStyle(file, index);
            return;
        }
    };
    let allowedExtension = ["image/jpeg", "image/jpg", "image/png", "video/mp4"];
    const handleImageStyle = async (file, index) => {
        if (allowedExtension.indexOf(file.type) < 0) {
            toast.error("Vui lòng chọn lại ảnh có định dạng .png, .jpg, .jpeg");
            return;
        }
        if (file) {
            images.value[index].isLoading = true;
            let imagePromise = new Promise(function (resolve) {
                const reader = new FileReader();
                reader.onload = () => {
                    let objectURL = URL.createObjectURL(file);
                    resolve(objectURL);
                };
                reader.readAsDataURL(file);
            });
            const s3_url = await getS3URL(file)
            imagePromise.then(function (value) {
                let image = {
                    imageRef: {
                        s3_url: s3_url,
                    },
                    isLoading: false
                };
                saveImage(image, index)
            });
        }
    };
    const getS3URL = async (file) => {
        const formData = new FormData();
        formData.append("image_file", file);
        try {
            const response = await axios.post(route("short-video.uploadImageToS3"), formData, {
                headers: {
                    "Content-Type": "multipart/form-data",
                },
            });
            if (response.data.success) {
                return response.data.s3_url
            } else {
                return ""
            }
        } catch (err) {
            return ""
        }
    }
    const saveImage = (image, index = -1) => {
        if(index > -1) {
            images.value[index] = image;
            images.value[index].isLoading = false
            images.value[index].is_post = false
            updateData()
            return
        }
        var isSave = false
        for(var i = 0; i < images.value.length; i++) {
            if(!images.value[i].previewImageUpload && !images.value[i].imageRef && !isSave) {
                isSave = true
                images.value[i] = image;
                images.value[i].isLoading = false
                images.value[i].is_post = false
            }
        }
        updateData()
    }

    const updateData = (isTick = false) => {
        eventBus.emit('updateImages', images);
        const formData = new FormData()
        formData.append("id", facebookContentDetail.value.id)
        formData.append("images", JSON.stringify(images.value))
        if(isTick) {
            formData.append("is_video", 2)
        }
        emit('updateFacebookContent', formData);
    }

    const removeImage = (index) => {
        images.value[index].imageRef = ""
        images.value[index].is_post = false
        updateData()
    }
    const showSearchModal = ref(false);
    const selectedSearchImage = ref(null);
    const currentSearchIndex = ref(null);
    const currentSearchIndexImage = ref(null);
    const openSearchModal = (index, index_image) => {
        currentSearchIndex.value = index;
        currentSearchIndexImage.value = index_image;
        showSearchModal.value = true;
        searchImages.value = [];
        currentPage.value = 1;
        searchImageByKeyword();
    };
    const isLoadingMore = ref(false);
    const loadMoreImages = async () => {
        if (isLoadingMore.value) return;
        isLoadingMore.value = true;
        currentPage.value += 1;
        await searchImageByKeyword();
        isLoadingMore.value = false;
    };
    const searchImageByKeyword = async (isAuto = false) => {
        try {
            const response = await axios.get(route("ai-business.search-image"), {
                params: {
                    keyword: selectedProject.value.title,
                    color_type: colorType.value,
                    page: currentPage.value,
                    site: selectedProject.value.url || "",
                },
            });
            const loadedImages = [];
            for (const img of response.data.items) {
                const imageUrl = img.link;
                const canLoad = await canLoadImage(imageUrl);
                if (canLoad) {
                    loadedImages.push(img);
                }
            }
            if(isAuto) {
                if(loadedImages.length >= 4) {
                    for(var i = 0; i < 4; i++) {
                        const image = {
                            imageRef: {
                                s3_url: loadedImages[i].link,
                                is_post:true
                            }
                        };
                        images.value[i] = image
                    }
                    updateData()
                }

            }
            if (currentPage.value === 1) {
                searchImages.value = loadedImages;
            } else {
                searchImages.value = [...searchImages.value, ...loadedImages];
            }
        } catch (error) {
            console.error("Lỗi khi tìm kiếm ảnh:", error);
        }
    };
    const confirmSelectedImage = () => {
        const index = currentSearchIndex.value;
        const index_image = currentSearchIndexImage.value;
        const image = {
            imageRef: {
                s3_url: selectedSearchImage.value,
            },
        };
        saveImage(image, index_image)
        showSearchModal.value = false;
    };
    //type_image: 0.Ảnh tạo từ AI; 1. Ảnh phối cảnh của sản phẩm; 2. Ảnh ghép người mẫu với sản phẩm, 3. Ảnh ghép tự sướng của bạn với sản phẩm, 4. Ảnh tìm kiếm từ internet
    const label_images = ref(['Ảnh tạo từ AI', 'Ảnh phối cảnh của sản phẩm', 'Ảnh ghép người mẫu với sản phẩm', 'Ảnh ghép tự sướng của bạn với sản phẩm', 'Ảnh tìm kiếm từ internet']);
    const generateCustomeImage = async (index, isAuto = false) => {
        await updateImageType(isAuto)
        await createImageBy(index)
    };

    const updateImageType = async (isAuto = false) => {
        var modelProject = selectedProject.value?.model_product
        var imageProject = selectedProject.value?.image_product
        for(var i = 0; i < images.value.length; i++) {
            if(!imageProject && !modelProject) {
                if(isAuto) {
                    images.value[i].type_image = 4
                } else {
                    images.value[i].type_image = 0
                }
            } else {
                images.value[i].type_image = 2
                if(i == 0) {
                    images.value[i].type_image = 1
                } else if(imageProject && modelProject) {
                    if(i > 1) {
                        images.value[i].type_image = 3
                    }
                }
            }
        }
    }
    const createImageBy = async (index) => {
        const modelProject = selectedProject.value?.model_product;
        const imageProject = selectedProject.value?.image_product;
        const i = index;
        let s3_url = images.value[i].imageRef ? images.value[i].imageRef.s3_url : '';
        images.value[i].isLoading = true
        if (images.value[i].type_image  == 1) {
            const imageProjectFile = await convertUrlToFile(imageProject)
            if(!imageProjectFile) {
                return null
            }
            s3_url = await generatePromptPerspective(imageProjectFile);
        } else if(images.value[i].type_image  == 0) {
            s3_url = await createAIImage();
        } else if(images.value[i].type_image  == 2) {
           s3_url = await createImageV2(imageProject, modelProject);
        } else if(images.value[i].type_image  == 3) {
            let model_link = await generateSelfImage();
            if(model_link) {
                s3_url = await createImageV2(imageProject, model_link);
            } else {
                images.value[i].type_image = 2;
                s3_url = await createImageV2(imageProject, modelProject);
            }
        }
        if (s3_url) {
            if (typeof images.value[i].imageRef !== 'object') {
                images.value[i].imageRef = {};
            }
            images.value[i].imageRef.s3_url = s3_url;
        }
        images.value[i].isLoading = false;
        updateData();
    };

    const createAIImage = async (index) => {
        let s3_url = '';
        try {
            const content = facebookContentDetail.value.content
            const response = await axios.post(route("ai-image.generate"), {
                description: `${content} ${prompts.value[0]}`,
                style: "Thực tế",
                artist: "Leonardo da Vinci",
                height: 1024,
                width: 1024,
                model: "Flux Schnell",
                aspect_ratio: "1:1",
            });
            return response.data.url;
        } catch (error) {
            console.error('Lỗi tạo ảnh:', error);
            toast.error('Tạo ảnh không thành công. Vui lòng thử lại.');
            return s3_url
        }
    }
    const generatePromptPerspective = async (imageFile) => {
        try {
            let formData = new FormData();
            formData.append("image_url", imageFile);
            const response = await axios.post(route("ai-business.generate-prompt-image"), formData, {
                headers: { "Content-Type": "multipart/form-data" },
            });
            if (response.data.status === "success") {
                var promptBackground = response.data.response;
                // Wait for generateAiBackground to return the URL
                return await generateAiBackground(imageFile, promptBackground); // It will return the URL from generateAiBackground
            } else {
                toast.error("Lỗi khi tạo phối cảnh: " + response.data.message);
                toast.error('Tạo ảnh không thành công. Vui lòng thử lại.');
                return null; // Return null if the response is not successful
            }
        } catch (error) {
            toast.error("Lỗi khi gọi API tạo phối cảnh!");
            toast.error('Tạo ảnh không thành công. Vui lòng thử lại.');
            return null; // Return null on error
        }
    };
    const generateAiBackground = async (imageProjectFile, promptBackground) => {
        try {
            let formData = new FormData();
            formData.append("prompt_background", promptBackground);
            formData.append("imageFile", imageProjectFile);
            const response = await axios.post(route("ai-background.generate-ai-background-v2"), formData, {
                headers: { "Content-Type": "multipart/form-data" },
            });
            if (response.data.s3_url) {
                // genBackgroundProductImage.value = response.data.s3_url;
                return response.data.s3_url; // Return the URL if successful
            } else {
                toast.error("Lỗi khi tạo nền AI: " + response.data.message);
                toast.error('Tạo ảnh không thành công. Vui lòng thử lại.');
                return null; // Return null if the URL is not available
            }
        } catch (error) {
            toast.error("Lỗi khi gọi API tạo nền AI!");
            toast.error('Tạo ảnh không thành công. Vui lòng thử lại.');
            return null; // Return null on error
        }
    };
    const DEFAULT_MODEL_IMAGE = "https://static2.yan.vn/YanNews/202308/202308020439097760-40d2f3e9-8f57-407c-bfb2-504fdd0ead22.jpeg";
    const convertUrlToFile = async (s3_image_url) => {
        var url = route("ai-image.showImage", { s3_url:s3_image_url})
        const response = await axios.get(url);
        if (response.data.success) {
            var imageUrl = 'data:image/jpeg;base64,'+response.data.data;
            return base64ToFile(imageUrl, 'image.jpg', "image/jpg")
        } else {
            return ""
        }
    };
    const base64ToFile = async (base64, filename, mimeType) => {
        const arr = base64.split(',');
        const bstr = atob(arr[1]); // decode base64
        let n = bstr.length;
        const u8arr = new Uint8Array(n);
        while (n--) {
            u8arr[n] = bstr.charCodeAt(n);
        }
        return new File([u8arr], filename, { type: mimeType });
    }
    const createImageV2 = async (imageProduct, modelProduct) => {
        let formData = new FormData();
        formData.append("model_product", modelProduct);
        formData.append("image_product", imageProduct);
        try {
            const response = await axios.post(route('ai-business.create-image'), formData, {
                headers: { "Content-Type": "multipart/form-data" },
            });
            if (response.data.s3_url) {
                return response.data.s3_url;
            } else {
                toast.error(response.data.message);
            }
        } catch (error) {
            toast.error("Lỗi khi kết hợp ảnh!");
        }
    };

    // Ảnh tự sướng
    const generateSelfImage = async () => {
        try {
            const latestModelResponse = await axios.get(route('ai-image.get-latest-my-ai-image'));
            const latestModel = latestModelResponse.data?.data;
            if (!latestModel || !latestModel.id) {
                return "";
            }
            const modelId = latestModel.id;
            let formData = new FormData();
            formData.append("aspect_ratio", "9:16");
            formData.append("model_id", modelId);
            formData.append("image_description", "Hình ảnh một người mẫu ăn mặc thời trang, đẹp mắt và phù hợp với giới tính, đang đứng tạo dáng chuyên nghiệp với một tay đặt phía trước ở vị trí như thể đang giới thiệu hoặc tương tác với một vật thể. Bối cảnh xung quanh được thiết kế hài hòa với tư thế, ánh sáng đẹp, phong cách chụp ảnh tạp chí, chất lượng cao, toàn thân.");
            try {
                const response = await axios.post(route('ai-image.generate-my-ai-image'), formData, {
                    headers: {
                        "Content-Type": "multipart/form-data",
                    },
                });
                if (response.data?.generated_images?.s3_url) {
                    return response.data.generated_images.s3_url;
                } else {
                    return "";
                }
            } catch (error) {
                return "";
            }
        } catch (error) {
            return "";
        }
    };
    // Ảnh phối cảnh sản phẩm
    const generateImageBackground = async (inputImageFile) => {
        let formData = new FormData();
        formData.append("image", inputImageFile);
        try {
            const response = await axios.post(route('ai-business.generate-image-background'), formData, {
                headers: { "Content-Type": "multipart/form-data" },
            });
            if (response.data.status === 'success') {
                return response.data.s3_url;
            } else {
                console.warn("Tạo ảnh nền không thành công. Chuyển sang generatePromptPerspective.");
                return await generatePromptPerspective(inputImageFile);
            }
        } catch (error) {
            console.error(error);
            let s3url = await generatePromptPerspective(inputImageFile);
            if (s3url) {
                return s3url;
            }
            toast.error("Lỗi khi gọi API tạo ảnh nền!");
        }
    };

    const upscaleImage = async (index, s3_url) => {
        let imageUrl = s3_url;
        images.value[index].isLoading = true
        let fileBlob = await convertUrlToFile(imageUrl)
        let formData = new FormData();
        formData.append("image", fileBlob);
        try {
            const response = await axios.post(route('ai-business.upscale-image'), formData, {
                headers: { "Content-Type": "multipart/form-data" },
            });
            if (response.data.status === 'success') {
                images.value[index].imageRef.s3_url = response.data.s3_url;
                images.value[index].isLoading = false
                updateData();
            } else {
                toast.error("Làm nét ảnh không thành công. Vui lòng thử lại.");
            }
        } catch (error) {
            console.error(error);
            toast.error("Làm nét ảnh không thành công. Vui lòng thử lại.");
        } finally {
            images.value[index].isLoading = false;
        }
    }
    defineExpose({ saveImage, saveGenerationResult, autoCreateImage });
</script>
