export const systemThemes = [
    {id: 37, name: "Finesse", textColor: "#878175", headingColor: "#394D2E", backgroundColor: "#F3E4CF", slideColor: "#FEF5E6"},
    {id: 16, name: "Pearl", textColor: "#545456", headingColor: "#312f39", backgroundColor: "#ecedf2", slideColor: "#fafafc"},
    {id: 18, name: "Chisel", textColor: "#686868", headingColor: "#201a18", backgroundColor: "#f7f3f0", slideColor: "#ffffff"},
    {id: 19, name: "Creme", textColor: "#7e7a70", headingColor: "#484235", backgroundColor: "#decfbc", slideColor: "#f9f6ef"},
    {id: 21, name: "Consultant", textColor: "#575757", headingColor: "#142d48", backgroundColor: "#f0f0f0", slideColor: "#ffffff"},
    {id: 24, name: "Commons", textColor: "#595959", headingColor: "#020202", backgroundColor: "#f5f5f5", slideColor: "#ffffff"},
    {id: 26, name: "Dialogue", textColor: "#888888", headingColor: "#030303", backgroundColor: "#fafafa", slideColor: "#ffffff"},
    {id: 28, name: "Lavender", textColor: "#949399", headingColor: "#5755db", backgroundColor: "#f4f0ff", slideColor: "#fbfaff,}"},
    {id: 29, name: "Howlite", textColor: "#484848", headingColor: "#000000", backgroundColor: "#ededed", slideColor: "#ffffff"},
    {id: 31, name: "Kraft", textColor: "#5c5b54", headingColor: "#292823", backgroundColor: "#ddd6cc", slideColor: "#efece5"},
    {id: 33, name: "Oatmeal", textColor: "#464646", headingColor: "#30312d", backgroundColor: "#edeee8", slideColor: "#ffffff"},
    {id: 34, name: "Sage", textColor: "#707179", headingColor: "#4c5466", backgroundColor: "#ebf4f3", slideColor: "#ffffff"},
    {id: 35, name: "Ash", textColor: "#9b9b99", headingColor: "#1c1c1c", backgroundColor: "#efefef", slideColor: "#fcfcfc"},
    {id: 1, name: 'Dark Vortex', textColor: '#E5E0DF', headingColor: '#F2F2F3', backgroundColor: '#19191A', slideColor: '#050505'},
    {id: 2, name: 'Dark Lux', textColor: '#F9EEE7', headingColor: '#FFD9BE', backgroundColor: '#123332', slideColor: '#1C4241'},
    {id: 3, name: 'Dark Marine', textColor: '#E5E6EA', headingColor: '#FFFFFF', backgroundColor: '#080E26', slideColor: '#A8AFCC'},
    {id: 4, name: 'Dark Bonan Hale', textColor: '#B3B3B3', headingColor: '#FEFEFE', backgroundColor: '#000000', slideColor: '#1F1F1F'},
    {id: 5, name: 'Dark Blueberry', textColor: '#CFD7F5', headingColor: '#FFFFFF', backgroundColor: '#271C4E', slideColor: '#100C35'},
    {id: 6, name: 'Dark Founder', textColor: '#D6D9D7', headingColor: '#F7F7F8', backgroundColor: '#111213', slideColor: '#2D3133'},
    {id: 7, name: 'Dark Indigo', textColor: '#D4DCFA', headingColor: '#FFFFFF', backgroundColor: '#150D48', slideColor: '#0C0A33'},
    {id: 8, name: 'Dark Mystique', textColor: '#E0D6DE', headingColor: '#FBF3FA', backgroundColor: '#18181B', slideColor: '#0F0F10'},
    {id: 9, name: 'Dark Blue Steel', textColor: '#D6E5EF', headingColor: '#72B6FF', backgroundColor: '#171B21', slideColor: '#202733'},
    {id: 10, name: 'Dark Mocha', textColor: '#C9C2C0', headingColor: '#C49F8C', backgroundColor: '#302D2C', slideColor: '#464342'},
    {id: 11, name: 'Dark Bubble Gum', textColor: '#ABA4AA', headingColor: '#FA95AF', backgroundColor: '#121212', slideColor: '#1F1F1F'},
    {id: 12, name: 'Dark Bee Happy', textColor: '#FFE14D', headingColor: '#FFE14D', backgroundColor: '#1B1B1E', slideColor: '#27272B'},
    {id: 13, name: 'Dark Wine', textColor: '#D7AAA0', headingColor: '#FFB393', backgroundColor: '#421424', slideColor: '#5C2438'},
    {id: 14, name: 'Basic Dark', textColor: '#C5C1C0', headingColor: '#FFFFFF', backgroundColor: '#0C0C0C', slideColor: '#272525'},
    {id: 15, name: 'Dark Slate', textColor: '#D4D4D1', headingColor: '#F3F3F2', backgroundColor: '#22242A', slideColor: '#292C32'},
    {id: 17, name: "Vortex", textColor: "#7e7c7c", headingColor: "#eeeeee", backgroundColor: "#191919", slideColor: "#050505"},
    {id: 20, name: "Lux", textColor: "#dee3df", headingColor: "#e6d3bd", backgroundColor: "#1c4342", slideColor: "#133332"},
    {id: 22, name: "Marine", textColor: "#e1e4ef", headingColor: "#fffeff", backgroundColor: "#a8afcc", slideColor: "#080e26"},
    {id: 23, name: "Night Sky", textColor: "#cdcccb", headingColor: "#fffffc", backgroundColor: "#000018", slideColor: "#010012"},
    {id: 25, name: "Bonan Hale", textColor: "#a3a3a3", headingColor: "#fefefe", backgroundColor: "#000000", slideColor: "#1f1f1f"},
    {id: 27, name: "Founder", textColor: "#626566", headingColor: "#f4f5f7", backgroundColor: "#111214", slideColor: "#2d3134"},
    {id: 30, name: "Onyx", textColor: "#cfd3d4", headingColor: "#fdfeff", backgroundColor: "#191a1c", slideColor: "#111214"},
    {id: 32, name: "Blues", textColor: "#dbd4ea", headingColor: "#f1eff2", backgroundColor: "#02122c", slideColor: "#0a151b"},
    {id: 36, name: "Coal", textColor: "#bfbfbb", headingColor: "#EAEBE6", backgroundColor: "#0D0D0B", slideColor: "#1D1D1B"},
];

export const systemCardThemes = [
    {name: 'Black', textColor: "#FFF", headingColor: "#FFF", backgroundColor: "#F3E4CF", slideColor: "#000"},
    {name: 'Dark Gray', textColor: "#FFF", headingColor: "#FFF", backgroundColor: "#F3E4CF", slideColor: "#4D4d4d"},
    {name: 'Gray', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#808080"},
    {name: 'Light Gray', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#CCC"},
    {name: 'White Smoke', textColor: "#141FFF", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#F2F2F2"},
    {name: 'White', textColor: "#141FFF", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#FFF"},
    {name: 'Light Sun', textColor: "#141FFF", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#FCEC99"},
    {name: 'Peach', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#FFD1A7"},
    {name: 'Salmon', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#FAA1A1"},
    {name: 'Lavender', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#D8AFF8"},
    {name: 'Baby blue', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#AFCBF8"},
    {name: 'Pale green', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#AEE4BD"},
    {name: 'Gold', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#F9D933"},
    {name: 'Orange', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#FFA44F"},
    {name: 'Red', textColor: "#FFF", headingColor: "#FFF", backgroundColor: "#F3E4CF", slideColor: "#F44444"},
    {name: 'Purple', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#B05EF1"},
    {name: 'Blue', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#5E98F1"},
    {name: 'Green', textColor: "#000", headingColor: "#000", backgroundColor: "#F3E4CF", slideColor: "#5CC97B"},
    {name: 'Dark Goldenrod', textColor: "#FFF", headingColor: "#FFF", backgroundColor: "#F3E4CF", slideColor: "#957D00"},
    {name: 'Brown', textColor: "#FFF", headingColor: "#FFF", backgroundColor: "#F3E4CF", slideColor: "#995515"},
    {name: 'Maroon', textColor: "#FFF", headingColor: "#FFF", backgroundColor: "#F3E4CF", slideColor: "#910D0D"},
    {name: 'Dark Purple', textColor: "#FFF", headingColor: "#FFF", backgroundColor: "#F3E4CF", slideColor: "#5E208E"},
    {name: 'Midnight Blue', textColor: "#FFF", headingColor: "#FFF", backgroundColor: "#F3E4CF", slideColor: "#204C8E"},
    {name: 'Forest Green', textColor: "#FFF", headingColor: "#FFF", backgroundColor: "#F3E4CF", slideColor: "#1F7135"},
];
